/*
  # Add summary column to route_cache table

  1. Changes
    - Add summary jsonb column to route_cache table (if it exists)
    - Create route_cache table if it doesn't exist first

  2. Notes
    - This migration ensures route_cache table exists before adding the summary column
    - The summary column will store per-day metrics, version info, and timeline data

  FIXED VERSION: Corrected owner_id to user_id and handled potential conflicts
*/

-- First, create the route_cache table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.route_cache (
  trip_id uuid NOT NULL REFERENCES public.trips(id) ON DELETE CASCADE,
  day date NOT NULL,
  places jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (trip_id, day)
);

-- Enable RLS on route_cache table
ALTER TABLE public.route_cache ENABLE ROW LEVEL SECURITY;

-- Drop existing policy first, then create new one
DROP POLICY IF EXISTS "Users can manage route cache for their trips" ON public.route_cache;

-- Add RLS policies for route_cache (corrected user_id reference)
CREATE POLICY "Users can manage route cache for their trips"
  ON public.route_cache
  FOR ALL
  TO authenticated
  USING (
    trip_id IN (
      SELECT id FROM public.trips 
      WHERE user_id = auth.uid()
      UNION
      SELECT trip_id FROM public.trip_collaborators 
      WHERE user_id = auth.uid()
    )
  );

-- Now add the summary column if it doesn't exist
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'route_cache' 
    AND column_name = 'summary'
  ) THEN
    ALTER TABLE public.route_cache ADD COLUMN summary jsonb;
  END IF;
END $$;

-- Add other columns that might be missing from the previous migration
DO $$ 
BEGIN
  -- Add id column if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'route_cache' 
    AND column_name = 'id'
  ) THEN
    ALTER TABLE public.route_cache ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;
  END IF;
  
  -- Add updated_at column if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'route_cache' 
    AND column_name = 'updated_at'
  ) THEN
    ALTER TABLE public.route_cache ADD COLUMN updated_at timestamptz DEFAULT now();
  END IF;
END $$;

-- Create index for better performance if it doesn't exist
CREATE INDEX IF NOT EXISTS idx_route_cache_trip_day ON public.route_cache(trip_id, day);
