#!/bin/bash

echo "🔍 VERIFICACIÓN DE MIGRACIÓN - temp_migration.sql"
echo "=================================================="
echo ""
echo "📋 Contenido de la migración:"
echo ""
cat temp_migration.sql
echo ""
echo "📝 INSTRUCCIONES PARA APLICAR LA MIGRACIÓN:"
echo ""
echo "1. 🌐 Ve a tu dashboard de Supabase:"
echo "   https://supabase.com/dashboard/project/iwsuyrlrbmnbfyfkqowl/sql"
echo ""
echo "2. 📄 Copia el contenido del archivo temp_migration.sql"
echo ""
echo "3. 📝 Pégalo en el editor SQL de Supabase"
echo ""
echo "4. ▶️  Ejecuta la consulta (botón RUN)"
echo ""
echo "5. ✅ Verifica que se agregaron las columnas:"
echo "   - mobile_phone (text)"
echo "   - country_code (text)"
echo ""
echo "🔗 Link directo al SQL Editor:"
echo "https://supabase.com/dashboard/project/iwsuyrlrbmnbfyfkqowl/sql"
echo ""
echo "⚠️  IMPORTANTE: Esta migración es necesaria para que funcione"
echo "   correctamente el sistema de información personal."
echo ""
echo "📱 Los campos se usan para:"
echo "   - mobile_phone: número de teléfono sin prefijo (123 456 789)"
echo "   - country_code: prefijo del país (+34, +52, etc.)"
echo ""
